# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap

# UI generated by QTDesign
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 398)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.uploadedImg = QtWidgets.QLabel(self.centralwidget)
        self.uploadedImg.setGeometry(QtCore.QRect(0, 0, 591, 291))
        self.uploadedImg.setText("")
        self.uploadedImg.setPixmap(QtGui.QPixmap("imgs/logo.png"))
        self.uploadedImg.setScaledContents(True)
        self.uploadedImg.setObjectName("uploadedImg")

        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(210, 300, 161, 61))
        self.uploadButton.setObjectName("uploadButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CatOrDog?"))
        MainWindow.setStatusTip(_translate("MainWindow", "Upload an image to predict"))
        self.uploadButton.setStatusTip(_translate("MainWindow", "Upload an image to predict"))
        self.uploadButton.setText(_translate("MainWindow", "Browse image"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
